import React from 'react'

const Learnlazy = () => {
  return (
    <div>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. In facilisis, dui posuere feugiat dapibus, risus lacus tincidunt quam, nec vestibulum odio metus et ligula. Suspendisse non tortor vehicula, semper mauris eget, iaculis nisl. Ut rutrum est in rhoncus maximus. Pellentesque consequat quis dui non sollicitudin. Nullam aliquet nibh nec bibendum volutpat. Cras fermentum lobortis tempor. Vestibulum ac suscipit metus. Aliquam ornare justo id tellus commodo suscipit. Aenean felis erat, ullamcorper quis sagittis dictum, luctus congue dolor. Vestibulum auctor, urna a iaculis rutrum, felis sapien iaculis purus, eget dapibus arcu nulla eu elit.


Ut nec convallis neque. Proin vehicula tristique finibus. Curabitur pretium malesuada metus, et commodo lorem aliquet id. Proin fermentum, arcu non vestibulum rutrum, dui sapien porttitor ligula, eu ornare lorem nunc sit amet risus. Aliquam tincidunt, arcu at porta pellentesque, felis dolor fermentum leo, vitae malesuada est mauris sed justo. Suspendisse non nulla ac magna porttitor vehicula. Suspendisse eget egestas lacus, non convallis diam. In congue, dolor eu gravida egestas, risus quam congue neque, vel tempus lectus justo nec nisi. Nullam nec egestas
Integer ut porttitor sapien, convallis dictum metus. Etiam vulputate lectus sem, et ultricies magna semper ut. Morbi ullamcorper suscipit enim, nec auctor arcu ullamcorper id. Maecenas nec convallis ipsum. Suspendisse potenti. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nam pharetra, ipsum sed imperdiet finibus, lacus ligula porta tellus, eget aliquet tellus orci nec nisi. Ut iaculis lorem vel arcu tristique egestas. Curabitur luctus congue ultrices. Pellentesque hendrerit tellus ac nulla eleifend, ac rutrum nulla porttitor. Phasellus at nisl vitae erat tempor finibus sed non ex. Aliquam erat lorem, accumsan quis convallis nec, sollicitudin eu arcu. Vestibulum et eros vitae lectus fringilla aliquet. Phasellus quis purus at urna convallis scelerisque. Integer consequat congue risus, eu viverra dui molestie vitae. Pellentesque euismod dui in mauris consequat, a malesuada nunc bibendum.

Ut nec convallis neque. Proin vehicula tristique finibus. Curabitur pretium malesuada metus, et commodo lorem aliquet id. Proin fermentum, arcu non vestibulum rutrum, dui sapien porttitor ligula, eu ornare lorem nunc sit amet risus. Aliquam tincidunt, arcu at porta pellentesque, felis dolor fermentum leo, vitae malesuada est mauris sed justo. Suspendisse non nulla ac magna porttitor vehicula. Suspendisse eget egestas lacus, non convallis diam. In congue, dolor eu gravida egestas, risus quam congue neque, vel tempus lectus justo nec nisi. Nullam nec egestas metus. Cras ornare accumsan dignissim.

Curabitur ullamcorper felis et lobortis lacinia. Praesent aliquet lobortis erat, vel posuere nunc condimentum ac. Cras porta tellusLorem ipsum dolor sit amet, consectetur adipiscing elit. In facilisis, dui posuere feugiat dapibus, risus lacus tincidunt quam, nec vestibulum odio metus et ligula. Suspendisse non tortor vehicula, semper mauris eget, iaculis nisl. Ut rutrum est in rhoncus maximus. Pellentesque consequat quis dui non sollicitudin. Nullam aliquet nibh nec bibendum volutpat. Cras fermentum lobortis tempor. Vestibulum ac suscipit metus. Aliquam ornare justo id tellus commodo suscipit. Aenean felis erat, ullamcorper quis sagittis dictum, luctus congue dolor. Vestibulum auctor, urna a iaculis rutrum, felis sapien iaculis purus, eget dapibus arcu nulla eu elit.

Integer ut porttitor sapien, convallis dictum metus. Etiam vulputate lectus sem, et ultricies magna semper ut. Morbi ullamcorper suscipit enim, nec auctor arcu ullamcorper id. Maecenas nec convallis ipsum. Suspendisse potenti. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nam pharetra, ipsum sed imperdiet finibus, lacus ligula porta tellus, eget aliquet tellus orci nec nisi. Ut iaculis lorem vel arcu tristique egestas. Curabitur luctus congue ultrices. Pellentesque hendrerit tellus ac nulla eleifend, ac rutrum nulla porttitor. Phasellus at nisl vitae erat tempor finibus sed non ex. Aliquam erat lorem, accumsan quis convallis nec, sollicitudin eu arcu. Vestibulum et eros vitae lectus fringilla aliquet. Phasellus quis purus at urna convallis scelerisque. Integer consequat congue risus, eu viverra dui molestie vitae. Pellentesque euismod dui in mauris consequat, a malesuada nunc bibendum.

Ut nec convallis neque. Proin vehicula tristique finibus. Curabitur pretium malesuada metus, et commodo lorem aliquet id. Proin fermentum, arcu non vestibulum rutrum, dui sapien porttitor ligula, eu ornare lorem nunc sit amet risus. Aliquam tincidunt, arcu at porta pellentesque, felis dolor fermentum leo, vitae malesuada est mauris sed justo. Suspendisse non nulla ac magna porttitor vehicula. Suspendisse eget egestas lacus, non convallis diam. In congue, dolor eu gravida egestas, risus quam congue neque, vel tempus lectus justo nec nisi. Nullam nec egestas metus. Cras ornare accumsan dignissim.

Curabitur ullamcorper felis et lobortis lacinia. Praesent aliquet lobortis erat, vel posuere nunc condimentum ac. Cras porta tellusLorem ipsum dolor sit amet, consectetur adipiscing elit. In facilisis, dui posuere feugiat dapibus, risus lacus tincidunt quam, nec vestibulum odio metus et ligula. Suspendisse non tortor vehicula, semper mauris eget, iaculis nisl. Ut rutrum est in rhoncus maximus. Pellentesque consequat quis dui non sollicitudin. Nullam aliquet nibh nec bibendum volutpat. Cras fermentum lobortis tempor. Vestibulum ac suscipit metus. Aliquam ornare justo id tellus commodo suscipit. Aenean felis erat, ullamcorper quis sagittis dictum, luctus congue dolor. Vestibulum auctor, urna a iaculis rutrum, felis sapien iaculis purus, eget dapibus arcu nulla eu elit.

Integer ut porttitor sapien, convallis dictum metus. Etiam vulputate lectus sem, et ultricies magna semper ut. Morbi ullamcorper suscipit enim, nec auctor arcu ullamcorper id. Maecenas nec convallis ipsum. Suspendisse potenti. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nam pharetra, ipsum sed imperdiet finibus, lacus ligula porta tellus, eget aliquet tellus orci nec nisi. Ut iaculis lorem vel arcu tristique egestas. Curabitur luctus congue ultrices. Pellentesque hendrerit tellus ac nulla eleifend, ac rutrum nulla porttitor. Phasellus at nisl vitae erat tempor finibus sed non ex. Aliquam erat lorem, accumsan quis convallis nec, sollicitudin eu arcu. Vestibulum et eros vitae lectus fringilla aliquet. Phasellus quis purus at urna convallis scelerisque. Integer consequat congue risus, eu viverra dui molestie vitae. Pellentesque euismod dui in mauris consequat, a malesuada nunc bibendum.

Ut nec convallis neque. Proin vehicula tristique finibus. Curabitur pretium malesuada metus, et commodo lorem aliquet id. Proin fermentum, arcu non vestibulum rutrum, dui sapien porttitor ligula, eu ornare lorem nunc sit amet risus. Aliquam tincidunt, arcu at porta pellentesque, felis dolor fermentum leo, vitae malesuada est mauris sed justo. Suspendisse non nulla ac magna porttitor vehicula. Suspendisse eget egestas lacus, non convallis diam. In congue, dolor eu gravida egestas, risus quam congue neque, vel tempus lectus justo nec nisi. Nullam nec egestas metus. Cras ornare accumsan dignissim.

Curabitur ullamcorper felis et lobortis lacinia. Praesent aliquet lobortis erat, vel posuere nunc condimentum ac. Cras porta tellusLorem ipsum dolor sit amet, consectetur adipiscing elit. In facilisis, dui posuere feugiat dapibus, risus lacus tincidunt quam, nec vestibulum odio metus et ligula. Suspendisse non tortor vehicula, semper mauris eget, iaculis nisl. Ut rutrum est in rhoncus maximus. Pellentesque consequat quis dui non sollicitudin. Nullam aliquet nibh nec bibendum volutpat. Cras fermentum lobortis tempor. Vestibulum ac suscipit metus. Aliquam ornare justo id tellus commodo suscipit. Aenean felis erat, ullamcorper quis sagittis dictum, luctus congue dolor. Vestibulum auctor, urna a iaculis rutrum, felis sapien iaculis purus, eget dapibus arcu nulla eu elit.

Integer ut porttitor sapien, convallis dictum metus. Etiam vulputate lectus sem, et ultricies magna semper ut. Morbi ullamcorper suscipit enim, nec auctor arcu ullamcorper id. Maecenas nec convallis ipsum. Suspendisse potenti. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nam pharetra, ipsum sed imperdiet finibus, lacus ligula porta tellus, eget aliquet tellus orci nec nisi. Ut iaculis lorem vel arcu tristique egestas. Curabitur luctus congue ultrices. Pellentesque hendrerit tellus ac nulla eleifend, ac rutrum nulla porttitor. Phasellus at nisl vitae erat tempor finibus sed non ex. Aliquam erat lorem, accumsan quis convallis nec, sollicitudin eu arcu. Vestibulum et eros vitae lectus fringilla aliquet. Phasellus quis purus at urna convallis scelerisque. Integer consequat congue risus, eu viverra dui molestie vitae. Pellentesque euismod dui in mauris consequat, a malesuada nunc bibendum.

Ut nec convallis neque. Proin vehicula tristique finibus. Curabitur pretium malesuada metus, et commodo lorem aliquet id. Proin fermentum, arcu non vestibulum rutrum, dui sapien porttitor ligula, eu ornare lorem nunc sit amet risus. Aliquam tincidunt, arcu at porta pellentesque, felis dolor fermentum leo, vitae malesuada est mauris sed justo. Suspendisse non nulla ac magna porttitor vehicula. Suspendisse eget egestas lacus, non convallis diam. In congue, dolor eu gravida egestas, risus quam congue neque, vel tempus lectus justo nec nisi. Nullam nec egestas metus. Cras ornare accumsan dignissim.

Curabitur ullamcorper felis et lobortis lacinia. Praesent aliquet lobortis erat, vel posuere nunc condimentum ac. Cras porta tellusLorem ipsum dolor sit amet, consectetur adipiscing elit. In facilisis, dui posuere feugiat dapibus, risus lacus tincidunt quam, nec vestibulum odio metus et ligula. Suspendisse non tortor vehicula, semper mauris eget, iaculis nisl. Ut rutrum est in rhoncus maximus. Pellentesque consequat quis dui non sollicitudin. Nullam aliquet nibh nec bibendum volutpat. Cras fermentum lobortis tempor. Vestibulum ac suscipit metus. Aliquam ornare justo id tellus commodo suscipit. Aenean felis erat, ullamcorper quis sagittis dictum, luctus congue dolor. Vestibulum auctor, urna a iaculis rutrum, felis sapien iaculis purus, eget dapibus arcu nulla eu elit.

Integer ut porttitor sapien, convallis dictum metus. Etiam vulputate lectus sem, et ultricies magna semper ut. Morbi ullamcorper suscipit enim, nec auctor arcu ullamcorper id. Maecenas nec convallis ipsum. Suspendisse potenti. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nam pharetra, ipsum sed imperdiet finibus, lacus ligula porta tellus, eget aliquet tellus orci nec nisi. Ut iaculis lorem vel arcu tristique egestas. Curabitur luctus congue ultrices. Pellentesque hendrerit tellus ac nulla eleifend, ac rutrum nulla porttitor. Phasellus at nisl vitae erat tempor finibus sed non ex. Aliquam erat lorem, accumsan quis convallis nec, sollicitudin eu arcu. Vestibulum et eros vitae lectus fringilla aliquet. Phasellus quis purus at urna convallis scelerisque. Integer consequat congue risus, eu viverra dui molestie vitae. Pellentesque euismod dui in mauris consequat, a malesuada nunc bibendum.

Ut nec convallis neque. Proin vehicula tristique finibus. Curabitur pretium malesuada metus, et commodo lorem aliquet id. Proin fermentum, arcu non vestibulum rutrum, dui sapien porttitor ligula, eu ornare lorem nunc sit amet risus. Aliquam tincidunt, arcu at porta pellentesque, felis dolor fermentum leo, vitae malesuada est mauris sed justo. Suspendisse non nulla ac magna porttitor vehicula. Suspendisse eget egestas lacus, non convallis diam. In congue, dolor eu gravida egestas, risus quam congue neque, vel tempus lectus justo nec nisi. Nullam nec egestas metus. Cras ornare accumsan dignissim.

Curabitur ullamcorper felis et lobortis lacinia. Praesent aliquet lobortis erat, vel posuere nunc condimentum ac. Cras porta tellusLorem ipsum dolor sit amet, consectetur adipiscing elit. In facilisis, dui posuere feugiat dapibus, risus lacus tincidunt quam, nec vestibulum odio metus et ligula. Suspendisse non tortor vehicula, semper mauris eget, iaculis nisl. Ut rutrum est in rhoncus maximus. Pellentesque consequat quis dui non sollicitudin. Nullam aliquet nibh nec bibendum volutpat. Cras fermentum lobortis tempor. Vestibulum ac suscipit metus. Aliquam ornare justo id tellus commodo suscipit. Aenean felis erat, ullamcorper quis sagittis dictum, luctus congue dolor. Vestibulum auctor, urna a iaculis rutrum, felis sapien iaculis purus, eget dapibus arcu nulla eu elit.


Ut nec convallis neque. Proin vehicula tristique finibus. Curabitur pretium malesuada metus, et commodo lorem aliquet id. Proin fermentum, arcu non vestibulum rutrum, dui sapien porttitor ligula, eu ornare lorem nunc sit amet risus. Aliquam tincidunt, arcu at porta pellentesque, felis dolor fermentum leo, vitae malesuada est mauris sed justo. Suspendisse non nulla ac magna porttitor vehicula. Suspendisse eget egestas lacus, non convallis diam. In congue, dolor eu gravida egestas, risus quam congue neque, vel tempus lectus justo nec nisi. Nullam nec egestas metus. Cras ornare accumsan dignissim.

Curabitur ullamcorper felis et lobortis lacinia. Praesent aliquet lobortis erat, vel posuere nunc condimentum ac. Cras porta tellusLorem ipsum dolor sit amet, consectetur adipiscing elit. In facilisis, dui posuere feugiat dapibus, risus lacus tincidunt quam, nec vestibulum odio metus et ligula. Suspendisse non tortor vehicula, semper mauris eget, iaculis nisl. Ut rutrum est in rhoncus maximus. Pellentesque consequat quis dui non sollicitudin. Nullam aliquet nibh nec bibendum volutpat. Cras fermentum lobortis tempor. Vestibulum ac suscipit metus. Aliquam ornare justo id tellus commodo suscipit. Aenean felis erat, ullamcorper quis sagittis dictum, luctus congue dolor. Vestibulum auctor, urna a iaculis rutrum, felis sapien iaculis purus, eget dapibus arcu nulla eu elit.

Integer ut porttitor sapien, convallis dictum metus. Etiam vulputate lectus sem, et ultricies magna semper ut. Morbi ullamcorper suscipit enim, nec auctor arcu ullamcorper id. Maecenas nec convallis ipsum. Suspendisse potenti. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nam pharetra, ipsum sed imperdiet finibus, lacus ligula porta tellus, eget aliquet tellus orci nec nisi. Ut iaculis lorem vel arcu tristique egestas. Curabitur luctus congue ultrices. Pellentesque hendrerit tellus ac nulla eleifend, ac rutrum nulla porttitor. Phasellus at nisl vitae erat tempor finibus sed non ex. Aliquam erat lorem, accumsan quis convallis nec, sollicitudin eu arcu. Vestibulum et eros vitae lectus fringilla aliquet. Phasellus quis purus at urna convallis s metus. Etiam vulputate lectus sem, et ultricies magna semper ut. Morbi ullamcorper suscipit enim, nec auctor arcu ullamcorper id. Maecenas nec convallis ipsum. Suspendisse potenti. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nam pharetra, ipsum sed imperdiet finibus, lacus ligula porta tellus, eget aliquet tellus orci nec nisi. Ut iaculis lorem vel arcu tristique egestas. Curabitur luctus congue ultrices. Pellentesque hendrerit tellus ac nulla eleifend, ac rutrum nulla porttitor. Phasellus at nisl vitae erat tempor finibus sed non ex. Aliquam erat lorem, accumsan quis convallis nec, sollicitudin eu arcu. Vestibulum et eros vitae lectus fringilla aliquet. Phasellus quis purus at urna convallis scelerisque. Integer consequat congue risus, eu viverra dui molestie vitae. Pellentesque euismod dui in mauris consequat, a malesuada nunc bibend
Ut nec convallis neque. Proin vehicula tristique finibus. Curabitur pretium malesuada metus, et commodo lorem aliquet id. Proin fermentum, arcu non vestibulum rutrum, dui sapien porttitor ligula, eu ornare lorem nunc sit amet risus. Aliquam tincidunt, arcu at porta pellentesque, felis dolor fermentum leo, vitae malesuada est mauris sed justo. Suspendisse non nulla ac magna porttitor vehicula. Suspendisse eget egestas lacus, non convallis diam. In congue, dolor eu gravida egestas, risus quam congue neque, vel tempus lectus justo nec nisi. Nullam nec egestas metus. Cras ornare accumsan dignissim.

Curabitur ullamcorper felis et lobortis lacinia. Praesent aliquet lobortis erat, vel posuere nunc condimentum ac. Cras porta tellusLorem ipsum dolor sit amet, consectetur adipiscing elit. In facilisis, dui posuere feugiat dapibus, risus lacus tincidunt quam, nec vestibulum odio metus et ligula. Suspendisse non tortor vehicula, semper mauris eget, iaculis nisl. Ut rutrum est in rhoncus maximus. Pellentesque consequat quis dui non sollicitudin. Nullam aliquet nibh nec bibendum volutpat. Cras fermentum lobortis tempor. Vestibulum ac suscipit metus. Aliquam ornare justo id tellus commodo suscipit. Aenean felis erat, ullamcorper quis sagittis dictum, luctus congue dolor. Vestibulum auctor, urna a iaculis rutrum, felis sapien iaculis purus, eget dapibus arcu nulla eu elit.

Integer ut porttitor sapien, convallis dictum metus. Etiam vulputate lectus sem, et ultricies magna semper ut. Morbi ullamcorper suscipit enim, nec auctor arcu ullamcorper id. Maecenas nec convallis ipsum. Suspendisse potenti. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nam pharetra, ipsum sed imperdiet finibus, lacus ligula porta tellus, eget aliquet tellus orci nec nisi. Ut iaculis lorem vel arcu tristique egestas. Curabitur luctus congue ultrices. Pellentesque hendrerit tellus ac nulla eleifend, ac rutrum nulla porttitor. Phasellus at nisl vitae erat tempor finibus sed non ex. Aliquam erat lorem, accumsan quis convallis nec, sollicitudin eu arcu. Vestibulum et eros vitae lectus fringilla aliquet. Phasellus quis purus at urna convallis scelerisque. Integer consequat congue risus, eu viverra dui molestie vitae. Pellentesque euismod dui in mauris consequat, a malesuada nunc bibendum.

Ut nec convallis neque. Proin vehicula tristique finibus. Curabitur pretium malesuada metus, et commodo lorem aliquet id. Proin fermentum, arcu non vestibulum rutrum, dui sapien porttitor ligula, eu ornare lorem nunc sit amet risus. Aliquam tincidunt, arcu at porta pellentesque, felis dolor fermentum leo, vitae malesuada est mauris sed justo. Suspendisse non nulla ac magna porttitor vehicula. Suspendisse eget egestas lacus, non convallis diam. In congue, dolor eu gravida egestas, risus quam congue neque, vel tempus lectus justo nec nisi. Nullam nec egestas metus. Cras ornare accumsan dignissim.

Curabitur ullamcorper felis et lobortis lacinia. Praesent aliquet lobortis erat, vel posuere nunc condimentum ac. Cras porta tellus</p>
    </div>
  )
}

export default Learnlazy;
